# Generated by Django 2.2.14 on 2020-07-10 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seekers_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('description', models.CharField(max_length=1024)),
                ('posted_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
