# Generated by Django 2.2.14 on 2020-07-17 19:29

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seekers_home', '0002_room_seeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='apartment_type',
            field=models.CharField(choices=[('Furnished', 'Furnished'), ('Semi furnished', 'Semi furnished'), ('Non furnished', 'Non furnished')], default='Non furnished', max_length=30),
        ),
        migrations.AddField(
            model_name='rooms',
            name='available_for',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Anysex', 'Anysex'), ('Single', 'Single'), ('Couple', 'Couple'), ('Anyone', 'Anyone')], default='Anyone', max_length=39),
        ),
    ]
