# Generated by Django 2.2.14 on 2020-07-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers_home', '0003_auto_20200717_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='contract',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='rooms',
            name='duration',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='rooms',
            name='duration_m_w_d',
            field=models.CharField(choices=[('Month', 'Month/s'), ('Week', 'Week/s'), ('Day', 'Day/s')], default='Month/s', max_length=10),
        ),
        migrations.AddField(
            model_name='rooms',
            name='guarantor_required',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
