# Generated by Django 2.2.14 on 2020-07-19 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seekers_home', '0004_auto_20200718_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='apl_caf',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='rooms',
            name='posted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='duration_m_w_d',
            field=models.CharField(choices=[('Month/s', 'Month/s'), ('Week/s', 'Week/s'), ('Day/s', 'Day/s')], default='Month/s', max_length=10),
        ),
    ]
