# Generated by Django 2.2.14 on 2020-07-23 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seekers_home', '0005_auto_20200719_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_seeker',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
